//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Titanbrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartXBook
    {
        public System.Guid CartID { get; set; }
        public System.Guid BookID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Book Book { get; set; }
    }
}
