CREATE TABLE [dbo].[Cart]
(
	
	[CartID]	UNIQUEIDENTIFIER NOT NULL,
	[UserID]	UNIQUEIDENTIFIER NOT NULL,
	[Date]		DATETIME NULL,
	[BookList]	NVARCHAR(36)

    CONSTRAINT [PK_MainCartTable] PRIMARY KEY ([CartID])
)
